### ISSUE TITLE
Passer en compatibilité Python 3

### ISSUE THREAD

**Issue by Luthaf** [patacrep/patanet#100]
En lien avec l'effort effectué pour patacrep, il faudrait passer en mode de compatibilité python 3. Les librairies gênantes sont : 
- [x] GitPython, qui est en cours de portage
- [x] Background_tasks, qui peut être remplacé par celery.
- [x] Il faudra aussi passer un coup de 2to3 sur notre propre code

**Comment by Luthaf** [comment]
> Background_tasks, qui peut être remplacé par celery.

Bon, je viens de regarder plus précisément, et Celery ressemble quand même à de l'artillerie lourde ...

Le problème c'est que Background_tasks est vraiment vieux (dernière mise à jour en 2011). Du coup, il reste comme alternative quelque chose basé sur Redis. Qu'en pensez-vous ? Trop compliqué à utiliser ? Trop lourd à lancer ? Bien ?

**Comment by ecnicolas** [comment]
Pour redis, je n'ai jamais utilisé, mais j'ai vu [ce post de blog](http://sametmax.com/redis-pourquoi-et-comment/) récemment qui est assez élogieux, et présente pas mal d'exemples.

**Comment by Luthaf** [comment]
On a les mêmes sources ^^

Après ça ajoute un peu de dépendances pour le dev, donc l’environnement est plus long à mettre en place.

**Comment by Luthaf** [comment]
Bon, finalement, il était beaucoup plus simple de mettre à jour Background tasks plutôt que tout modifier.

La PR est ici : https://github.com/lilspikey/django-background-task/pull/12. Si jamais elle n'est pas mergée rapidement, on pourra héberger notre propre version.

Le reste du code est déjà en majorité compatible Python 3, mais il faut encore mettre à jour le code avec  la nouvelle version de patacrep.

**Comment by Luthaf** [comment]
La branche python3 se lance à nouveau, et la compilation des carnets fonctionne ! Par contre, le rendu des chansons HTML en LaTeX est mort avec le passage à Python 3. Je pense que je vais rétablir la version JS en attendant le passage de patadata à ChordPro.

**Comment by oliverpool** [comment]
Je n'arrive pas à importer des chants avec importsong...

**Comment by Luthaf** [comment]
Arf ... Tu as quoi comme erreur ?

**Comment by oliverpool** [comment]
```
 Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/oliverpool/virtualacrep/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/oliverpool/virtualacrep/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/oliverpool/virtualacrep/lib/python3.4/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/oliverpool/virtualacrep/lib/python3.4/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/media/sf_patacrep/patanet/generator/management/commands/importsongs.py", line 21, in <module>
    from generator.management.songs import import_song
  File "/media/sf_patacrep/patanet/generator/management/songs.py", line 23, in <module>
    from patacrep.plastex import parsetex
  File "/home/oliverpool/virtualacrep/lib/python3.4/site-packages/patacrep/plastex.py", line 5, in <module>
    from plasTeX.TeX import TeX
  File "/home/oliverpool/virtualacrep/lib/python3.4/site-packages/plasTeX/__init__.py", line 217
    raise AttributeError, 'could not find attribute title'
                        ^
SyntaxError: invalid syntax
```

**Comment by Luthaf** [comment]
En effet ... On utilisait plastex pour parser les chansons, mais je croyais avoir viré ce bout de code.

Plastex n'est pas compatible Python3.

**Comment by Luthaf** [comment]
Ok, ça devrait être fixé maintenant https://github.com/patacrep/patanet/commit/95f347b19b134a22858aedfd42f4563fb2c5142c. Il faut la dernière version de patacrep par contre, pas celle sur PyPi

```
pip install git+https://github.com/patacrep/patacrep.git
```

**Comment by oliverpool** [comment]
cool!
merci
